// PT -> EN para o conteudo dos slides (deck.ts). Fallback para PT quando ausente.
export const EN: Record<string, string> = {
  "Pseudonimização segura e escalável de dados de incidentes e vulnerabilidades em CSIRTs": "Secure and scalable pseudonymization of incident and vulnerability data in CSIRTs",
  "Orientador: Diego Kreutz": "Advisor: Diego Kreutz",
  "Ciência da Computação, UNIPAMPA, Campus Alegrete": "Computer Science, UNIPAMPA, Campus Alegrete",
  "O que é um CSIRT?": "What is a CSIRT?",
  "A equipe que cuida da segurança digital. ": "The team that takes care of digital security. ",
  "Como os bombeiros, mas para ataques digitais.": "Like firefighters, but for digital attacks.",
  "Recebe": "Receives",
  "alertas de ataques e falhas": "alerts of attacks and failures",
  "Investiga": "Investigates",
  "o que aconteceu e o impacto": "what happened and the impact",
  "Responde": "Responds",
  "contém e corrige o problema": "contains and fixes the problem",
  "Vulnerabilidades de rede": "Network vulnerabilities",
  "Varreduras": "Scans",
  "de vulnerabilidades": "of vulnerabilities",
  "De rede, não de código": "Of the network, not the code",
  "host, portas e serviços": "host, ports and services",
  "Raio-X da rede": "X-ray of the network",
  "revela portas e fraquezas": "reveals ports and weaknesses",
  "Registros de incidentes": "Incident records",
  "Tickets de incidente": "Incident tickets",
  "ataques já detectados": "attacks already detected",
  "Vêm dos CSIRTs": "Come from the CSIRTs",
  "Expõem a vítima": "Expose the victim",
  "e-mails, nomes, IPs": "emails, names, IPs",
  "A escala do problema: vulnerabilidades": "The scale of the problem: vulnerabilities",
  "O número de vulnerabilidades cresce muito mais rápido que a capacidade de analisá-las.": "The number of vulnerabilities grows much faster than the capacity to analyze them.",
  "CVEs publicados por ano  (*previsão)": "CVEs published per year  (*forecast)",
  "Crise de enriquecimento da NVD/NIST (2026)": "NVD/NIST enrichment crisis (2026)",
  "A NIST só analisa os CVEs prioritários. O resto fica sem classificação, e sobra para o CSIRT local.": "NIST only analyzes the priority CVEs. The rest goes unclassified, and it is left to the local CSIRT.",
  "A escala do problema: incidentes": "The scale of the problem: incidents",
  "As notificações de incidentes saltaram de milhares para milhões em duas décadas.": "Incident notifications jumped from thousands to millions in two decades.",
  "3,1 mil": "3.1k",
  "875 mil": "875k",
  "2,3 mi": "2.3M",
  "Notificações de incidentes ao CERT.br, por ano (CERT.br/NIC.br)": "Incident notifications to CERT.br, per year (CERT.br/NIC.br)",
  "A capacidade não acompanha": "Capacity is not keeping up",
  "Déficit global de ~4,8 milhões de profissionais de segurança. Cada registro tratado por uma CSIRT carrega dados pessoais a proteger.": "Global deficit of ~4.8 million security professionals. Each record handled by a CSIRT carries personal data to protect.",
  "Automação com IA": "Automation with AI",
  "LLMs que ": "LLMs that ",
  "priorizam, classificam e sugerem respostas.": "prioritize, classify and suggest responses.",
  "Sensibilidade dos dados": "Data sensitivity",
  "Identificadores de rede": "Network identifiers",
  "IP, hostname, certificado": "IP, hostname, certificate",
  "Dados pessoais": "Personal data",
  "nomes e e-mails das vítimas": "names and emails of the victims",
  "Perigoso se vazar": "Dangerous if leaked",
  "expõe a rede e fere a LGPD": "exposes the network and violates the LGPD",
  "Como preparar esses dados para usar a IA com ": "How to prepare this data to use AI with ",
  "segurança": "security",
  ", em ": ", at ",
  "escala": "scale",
  ", sem perder a ": ", without losing ",
  "utilidade": "utility",
  "A resposta deste trabalho: pseudonimização.": "This work's answer: pseudonymization.",
  "O que é uma entidade?": "What is an entity?",
  "Um tipo reconhecido": "A recognized type",
  "um dado pessoal ou um artefato técnico": "a piece of personal data or a technical artifact",
  "Exemplos de entidade": "Entity examples",
  "IP, hostname, nome, hash, certificado": "IP, hostname, name, hash, certificate",
  "Exemplo: antes e depois (Tenable)": "Example: before and after (Tenable)",
  "Anonimizado": "Anonymized",
  "Vermelho: sensível   ·   ": "Red: sensitive   ·   ",
  "Teal: pseudonimizado   ·   ": "Teal: pseudonymized   ·   ",
  "Preto: preservado   ·   ": "Black: preserved   ·   ",
  "campos do Tenable (exemplos)": "Tenable fields (examples)",
  "O pipeline de pseudonimização": "The pseudonymization pipeline",
  "Estágio 1: Entrada": "Stage 1: Input",
  "O sistema lê vários formatos. Arquivos grandes são lidos em fluxo.": "The system reads several formats. Large files are read as a stream.",
  "Leitura em fluxo (streaming)": "Stream reading (streaming)",
  "Estágio 2: Detecção (NER)": "Stage 2: Detection (NER)",
  "o NER e o RegEx reconhecem o IP e o nome como entidades": "the NER and the RegEx recognize the IP and the name as entities",
  "Cache (vem antes)": "Cache (comes first)",
  "GPU no modelo NER": "GPU in the NER model",
  "Estágio 3: HMAC-SHA256": "Stage 3: HMAC-SHA256",
  "Cada entidade vira um pseudônimo gerado com uma chave secreta.": "Each entity becomes a pseudonym generated with a secret key.",
  "o prefixo guarda o ": "the prefix holds the ",
  "tipo da entidade": "entity type",
  "; o resto é o ": "; the rest is the ",
  "hash gerado com a chave secreta": "hash generated with the secret key",
  "Estágios 4 e 5: Persistência e Saída": "Stages 4 and 5: Persistence and Output",
  "Persistência": "Persistence",
  "banco SQLite (tabela ": "SQLite database (table ",
  "): guarda o hash completo": "): stores the complete hash",
  "Tipo": "Type",
  "Pseudônimo": "Pseudonym",
  "Hash completo (64c)": "Complete hash (64c)",
  "Saída (ex.: XML)": "Output (e.g.: XML)",
  "estrutura mantida; sensíveis (teal) viram pseudônimo, o resto (preto) é preservado": "structure maintained; sensitive fields (teal) become pseudonyms, the rest (black) is preserved",
  "A linha de pesquisa AnonLFI": "The AnonLFI research line",
  "primeiro pipeline": "first pipeline",
  "de outra equipe (Bandel et al.)": "from another team (Bandel et al.)",
  "arquitetura extensível (WRSeg)": "extensible architecture (WRSeg)",
  "escala (SBRC, Salão Fer.)": "scale (SBRC, Tools Track)",
  "Evolução da linha AnonLFI": "Evolution of the AnonLFI line",
  "Linhas de código e número de módulos por versão.": "Lines of code and number of modules per version.",
  "361 linhas": "361 lines",
  "monolítico (1 módulo)": "monolithic (1 module)",
  "972 linhas": "972 lines",
  "5 módulos": "5 modules",
  "5.428 linhas": "5,428 lines",
  "17 módulos": "17 modules",
  "Motivação: a escala operacional": "Motivation: the operational scale",
  "70.951 vulnerabilidades": "70,951 vulnerabilities",
  "do CAIS/RNP": "from CAIS/RNP",
  "Antes: +92 horas": "Before: +92 hours",
  "inviável em escala": "unfeasible at scale",
  "Daí o AnonShield": "Hence AnonShield",
  "feito para escalar": "built to scale",
  "Conjuntos de dados": "Datasets",
  "Base": "Dataset",
  "Origem": "Source",
  "Formatos": "Formats",
  "Arquivos": "Files",
  "Tamanho": "Size",
  "Finalidade": "Purpose",
  "OpenVAS (laboratório VulnLab)": "OpenVAS (VulnLab laboratory)",
  "9 a 34 MB": "9 to 34 MB",
  "Acurácia e desempenho": "Accuracy and performance",
  "Conversão do D1 (outros formatos)": "Conversion of D1 (other formats)",
  "até 1,5 GB": "up to 1.5 GB",
  "Laboratório de serviços vulneráveis": "Laboratory of vulnerable services",
  "VulnLab: 130 containers Docker vulneráveis, em 11 categorias de serviços.": "VulnLab: 130 vulnerable Docker containers, in 11 service categories.",
  "Aplicações web vulneráveis · 21": "Vulnerable web applications · 21",
  "Rede e infraestrutura · 19": "Network and infrastructure · 19",
  "Bancos de dados · 17": "Databases · 17",
  "Servidores web e de aplicação · 17": "Web and application servers · 17",
  "Linguagens e runtimes · 12": "Languages and runtimes · 12",
  "CMS e plataformas web · 11": "CMS and web platforms · 11",
  "DevOps e CI/CD · 9": "DevOps and CI/CD · 9",
  "Sistemas operacionais · 8": "Operating systems · 8",
  "Monitoramento e logging · 6": "Monitoring and logging · 6",
  "Mensageria e streaming · 5": "Messaging and streaming · 5",
  "CVEs específicos · 5": "Specific CVEs · 5",
  "Varredura com OpenVAS": "Scanning with OpenVAS",
  "Cada container é varrido com OpenVAS/GVM (Greenbone); os relatórios formam o D1.": "Each container is scanned with OpenVAS/GVM (Greenbone); the reports make up D1.",
  "Cria alvo": "Create target",
  "Cria tarefa": "Create task",
  "Varre": "Scan",
  "Monitora (30s)": "Monitor (30s)",
  "Baixa relatório": "Download report",
  " de varredura total     ": " of total scanning     ",
  " relatórios  (130 alvos × 4 formatos: PDF, XML, CSV, TXT)": " reports  (130 targets × 4 formats: PDF, XML, CSV, TXT)",
  "motor de varredura de vulnerabilidades": "vulnerability scanning engine",
  "Perfil Full and fast": "Full and fast profile",
  "~30 a 60 min por host": "~30 to 60 min per host",
  "Cobertura de portas": "Port coverage",
  "todas as portas IANA atribuídas (TCP e UDP)": "all assigned IANA ports (TCP and UDP)",
  "130 alvos": "130 targets",
  "cada container do VulnLab é varrido": "each VulnLab container is scanned",
  "Metodologia": "Methodology",
  "Amostra: 67 de 6.472 (D1)": "Sample: 67 of 6,472 (D1)",
  "90% confiança, 3 especialistas": "90% confidence, 3 experts",
  "13 tipos de entidades": "13 entity types",
  "avaliados manualmente": "evaluated manually",
  "Métricas": "Metrics",
  "Precisão, Recall (crítica), F1": "Precision, Recall (critical), F1",
  "Acurácia": "Accuracy",
  "Versão": "Version",
  "Precisão": "Precision",
  "32,4%": "32.4%",
  "18,8%": "18.8%",
  "23,8%": "23.8%",
  "80,9%": "80.9%",
  "40,7%": "40.7%",
  "54,2%": "54.2%",
  "91,7%": "91.7%",
  "96,1%": "96.1%",
  "93,8%": "93.8%",
  "Comparação na estratégia standalone (detecção própria do AnonShield: NER + RegEx). Modelo NER: SecureModernBERT.": "Comparison in the standalone strategy (AnonShield's own detection: NER + RegEx). NER model: SecureModernBERT.",
  "Tenable (CAIS/RNP, privado)": "Tenable (CAIS/RNP, private)",
  "Desempenho": "Performance",
  "Sintético (gêmeo público do D2)": "Synthetic (public twin of D2)",
  "Desempenho em escala operacional": "Performance at operational scale",
  "speedup sobre o AnonLFI 2.0": "speedup over AnonLFI 2.0",
  "ANTES  (AnonLFI 2.0, estimado)": "BEFORE  (AnonLFI 2.0, estimated)",
  "~92 horas": "~92 hours",
  "DEPOIS  (AnonShield)": "AFTER  (AnonShield)",
  "7,5 minutos": "7.5 minutes",
  "Reconhecimento": "Recognition",
  "Melhor Artefato do SBRC 2026": "Best Artifact of SBRC 2026",
  "Selecionado entre os 65 artefatos avaliados no evento.": "Selected among the 65 artifacts evaluated at the event.",
  "Selos de artefato concedidos": "Artifact badges granted",
  "Resultados da avaliação de artefatos (CTA)": "Results of the artifact evaluation (CTA)",
  "Utilidade analítica dos dados": "Analytical utility of the data",
  "Os dados pseudonimizados já sustentam pesquisa publicada:": "The pseudonymized data already support published research:",
  "Classificação automatizada de incidentes em SOCs com LLMs e engenharia de prompt.": "Automated classification of incidents in SOCs with LLMs and prompt engineering.",
  "Modelos de linguagem on-premise vs. comerciais para classificar incidentes em CSIRTs.": "On-premise vs. commercial language models for classifying incidents in CSIRTs.",
  "Melhor resultado: ": "Best result: ",
  "92,27% de acurácia": "92.27% accuracy",
  " dos comerciais": " of the commercial ones",
  "Trabalhos futuros (TCC II)": "Future work (TCC II)",
  "Avaliação comparativa entre dados pseudonimizados e originais, medindo o equilíbrio entre ": "Comparative evaluation between pseudonymized and original data, measuring the balance between ",
  "privacidade e utilidade": "privacy and utility",
  " na classificação de vulnerabilidades e incidentes com modelos de linguagem.": " in the classification of vulnerabilities and incidents with language models.",
  "Atividade": "Activity",
  "Ago": "Aug",
  "Set": "Sep",
  "Out": "Oct",
  "Nov": "Nov",
  "Dez": "Dec",
  "Preparação das bases e tarefas downstream": "Preparation of datasets and downstream tasks",
  "Implementação do pipeline de utilidade": "Implementation of the utility pipeline",
  "Ajuste fino com preservação de privacidade": "Fine-tuning with privacy preservation",
  "Execução de experimentos e análise": "Execution of experiments and analysis",
  "Redação e revisão do artigo final": "Writing and revision of the final paper",
  "Artigos e materiais": "Papers and materials",
  "código e artefatos": "code and artifacts",
  "Obrigado.": "Thank you.",
  "Apoio:": "Support:",
  "Cristhian Kapelinski  ·  Orientador: Diego Kreutz": "Cristhian Kapelinski  ·  Advisor: Diego Kreutz",
};
